#sudo: false # use containers

language: java

# Makes build faster to cache maven things.
cache:
  directories:
  - .autoconf
  - $HOME/.m2

# whitelist
branches:
 only:
  - master
 
jdk:
 - oraclejdk8

# Make a display for the tests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# Check they had a ticket with this change
before_install:
- chmod +x ./org.eclipse.richbeans.releng/build/commit-msg.sh
- bash ./org.eclipse.richbeans.releng/build/commit-msg.sh
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3 # give xvfb some time to start as per the travis docs
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  
# Run maven. This happens automatically and adding it again makes the build longer.
script: 
 - mvn clean install surefire:test -Dtest.includes=org/eclipse/richbeans/**/Suite.java -Dlog4j.configuration=log4j.properties
 
# Added deploy back to github
# This should publish to the tag on master called 'snapshot'
deploy:
  provider: releases
  api_key:
    secure: I5xPlT1AnFLRm89JeBKVAZdq52RFtxwu21BVgsKuGZ6TU50avgq5A5mx+0RSlj4qO3IsmqcG6Sf5psPvR7DOfFiGIViqANaaYp6N6yGFq1hMSgAOsm4M9CfTA94tpn/eb8EIPymvB/MCeyQjV+AF62BC1KAXLbTgIWr/neux0d4zeM16aimfGtjKvX9qcbFGnepgrU+WhBr2M1YEQvVa7Nzo2ulOkt2lcZKslNu+mjWGyIpTLepveQKD7gx425jALmo60Qpr8NkNkH6WxiNdKBhCKHBp5mBlPWLfZTY9F40ubSpLPvbMFnXsfryOxbeue1UoOKvnoKI3u+B57kTJrBcC0tjXdPaTD9SXaEYHK00VnkW1y+1IXAg/wBBbBMZNnMsTiElqT9rAwq3gz1YZYKMuzBLTLlrg134eXghFvaoKemZZGQbhkziZJ7aHhZmkNMptlu1GVO8/rOhXXcCFBwVaz0TAgmHRCvNrw+6uqwHRRpq85D64vfBjhicpVasQg5bLU+pOtxmrgvU+KI2dlVf0VLWp8yfmtNJDDNtm6gJ4xM/ESRKb+JUb1+YqXnYuGSFc7/6cmHOsDzwaOYmYScXNX1e7U61Ad4Y6Dup21b3Vkmb5xs7/MGQpCMYS4X+Jj/ulS2S0S6Gv58wA241f12NOuQxaNJAr2yJpQ/2pKAI=
  file: /home/travis/.m2/repository/org/eclipse/org.eclipse.richbeans.repository/1.0.0-SNAPSHOT/org.eclipse.richbeans.repository-1.0.0-SNAPSHOT.zip
  on:
    repo: eclipse/richbeans
    branch: master
    
